config/routes.rb
Rails.application.routes.draw do

  get "user_count",                   to: "main#user_count"
  get "users_mentioning_most_users",  to: "main#users_mentioning_most_users"
  get "most_mentioned_users",         to: "main#most_mentioned_users"
  get "most_active_users",            to: "main#most_active_users"
  get "top_ten_tweets",         to: "main#top_ten_tweets"

  root to: "main#landing_page"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet
  include Mongoid::Document
  store_in collection: "tweets"

  field :id, type: Integer
  field :polarity, type: Integer
  field :date, type: String
  field :query, type: String
  field :user, type: String
  field :text, type: String

  index({:"user" => 1}, {name: "user_index"})
  index({:"polariry" => 1}, {name: "polariry_index"})

  def self.user_count
    distinct('user').length
  end

  def self.users_mentioning_most_users
    collection.aggregate([
        {"$match": {"text": /@\w+/}},
        {"$group": {_id: "$user","text": {"$push": "$text"}}},
        {"$project": {_id: "$_id", "matches": {"$size": "$text"}}},
        {"$sort": {"matches": -1}},
        {"$limit": 10}
      ], :allow_disk_use => true)
  end

  def self.most_mentioned_users
    collection.aggregate([
      {"$match":{"text":/@\w+/}},
      {"$project": {"text": {"$split": ["$text", " "]}}},
      {"$unwind": "$text"},
      {"$match": {"text": /@\w+/}},
      {"$group": {_id: "$text", "occurrences": {"$sum": 1}}},
      {"$sort": {"occurrences": -1}},
      {"$limit": 10}
    ], :allow_disk_use => true)
  end

  def self.most_active_users_by_tweet_count
    collection.aggregate([
      {"$group": {"_id": "$user", "tweets": {"$sum": 1}}},
      {"$sort": {"tweets": -1}},
      {"$limit": 10}
    ], :allow_disk_use => true).to_a
  end

  def self.most_active_users_by_longest_tweet
    collection.aggregate([
      {"$project": {"_id": "$user", "tweet": "$text", "length": { "$strLenCP": "$text" }}},
      {"$sort": {"length": -1}},
      {"$limit": 10}
    ], :allow_disk_use => true).to_a
  end

  def self.most_negative_tweets
    collection.aggregate([
      {"$project": {"_id": "$user", "polarity": "$polarity", "tweet": "$text", "date": "$date"}},
      {"$sort": {"polarity": 1}},
      {"$limit": 10}
    ], :allow_disk_use => true).to_a
  end

  def self.most_positive_tweets
    collection.aggregate([
      {"$project": {"_id": "$user", "polarity": "$polarity", "tweet": "$text", "date": "$date"}},
      {"$sort": {"polarity": -1}},
      {"$limit": 10}
    ], :allow_disk_use => true).to_a
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "application"
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def landing_page
    respond_to do |format|
      format.html do
      end
    end
  end

  def user_count
    respond_to do |format|
      format.html do
        @user_count = Tweet.user_count
      end
    end
  end

  def most_active_users
    respond_to do |format|
      format.html do
        @most_active_users_by_tweet_count = Tweet.most_active_users_by_tweet_count
        @most_active_users_by_longest_tweet = Tweet.most_active_users_by_longest_tweet
      end
    end
  end

  def users_mentioning_most_users
    respond_to do |format|
      format.html do
        @users = Tweet.users_mentioning_most_users
      end
    end
  end

  def top_ten_tweets
    respond_to do |format|
      format.html do
        @most_positive_tweets = Tweet.most_positive_tweets
        @most_negative_tweets = Tweet.most_negative_tweets
      end
    end
  end

  def most_mentioned_users
    respond_to do |format|
      format.html do
        @most_mentioned_users = Tweet.most_mentioned_users
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalAssignment</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <div id="top-menu">
    <table>
      <tbody>
        <tr>
          <td><%= link_to("Antal brugere", user_count_path, id: "btn_antal_brugere", class: "btn btn-primary") %></td>
          <td><%= link_to("Top-10 refererende brugere", users_mentioning_most_users_path, id: "btn_top_10_referende_brugere", class: "btn btn-primary") %></td>
          <td><%= link_to("Top-10 populære brugere", most_mentioned_users_path, id: "btn_top_ten_mentioned_users", class: "btn btn-primary") %></td>
          <td><%= link_to("Top-10 aktive brugere", most_active_users_path, id: "btn_most_active_users", class: "btn btn-primary") %></td>
          <td><%= link_to("Top-10 indlæg", top_ten_tweets_path, id: "btn_top_ten_tweets", class: "btn btn-primary") %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div id="main-content">
    <%= yield %>
  </div>
</body>
</html>

app/views/main/landing_page.html.erb
Velkommen!

Brug menuen ovenover for at navigere rundt i systemet.

app/views/main/most_active_users.html.erb
<script>
function show(id) {
  $("#by_count, #by_length").addClass("hidden");
  $('#' + id).removeClass("hidden");
}
</script>
<button onclick="show('by_count');" type="button" class="btn btn-primary" id="btn_by_count">Antal tweets</button>
<button onclick="show('by_length');" type="button" class="btn btn-primary" id="btn_by_length">Længste besked</button>
<br><br>
<div id="by_count" class="hidden">
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th>Brugernavn</th>
        <th>Antal tweets</th>
      </tr>
    </thead>
    <tbody>
      <% @most_active_users_by_tweet_count.each do |user| %>
      <tr>
        <td><%= user['_id'] %></td>
        <td><%= user['tweets'] %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div id="by_length" class="hidden">
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th>Brugernavn</th>
        <th>Antal tegn i længste besked</th>
      </tr>
    </thead>
    <tbody>
      <% @most_active_users_by_longest_tweet.each do |user| %>
      <tr>
        <td><%= user['_id'] %></td>
        <td><%= user['length'] %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/main/most_mentioned_users.html.erb
<div>
  <h1>Top-10 nævnte brugere</h1>
  <br><br>
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th>Brugernavn</th>
        <th>Nævnt X antal gange</th>
      </tr>
    </thead>
    <tbody>
      <% @most_mentioned_users.each do |user| %>
      <tr>
        <td><%= user['_id'].gsub('@','') %></td>
        <td><%= user['occurrences'] %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/main/top_ten_tweets.html.erb
<script>
function show(id) {
  $("#positive, #negative").addClass("hidden");
  $('#' + id).removeClass("hidden");
}
</script>

<button id="btn_positive" onclick="show('positive');" type="button" class="btn btn-success">Top-10 positive</button>
<button id="btn_negative" onclick="show('negative');" type="button" class="btn btn-danger">Top-10 negative</button>
<br><br>
<div id="positive" class="hidden">
  <h3>Top-10 positive</h3>
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th>Brugernavn</th>
        <th>Polaritet</th>
        <th>Tweet</th>
      </tr>
    </thead>
    <tbody>
      <% @most_positive_tweets.each do |user| %>
      <tr>
        <td><%= user['_id'] %></td>
        <td><%= user['polarity'] %></td>
        <td><%= user['tweet'] %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div id="negative" class="hidden">
  <h3>Top-10 negative</h3>
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th>Brugernavn</th>
        <th>Polaritet</th>
        <th>Tweet</th>
      </tr>
    </thead>
    <tbody>
      <% @most_negative_tweets.each do |user| %>
      <tr>
        <td><%= user['_id'] %></td>
        <td><%= user['polarity'] %></td>
        <td><%= user['tweet'] %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/main/user_count.html.erb
<div>
  <h1>Antal brugere</h1>
  <h3 id="result"><%= @user_count %></h3>
</div>

app/views/main/users_mentioning_most_users.html.erb
<div>
  <h1>Top-10 brugere der oftest referer til andre brugere</h1>
  <br><br>
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th>Brugernavn</th>
        <th>Antallet af nævnte brugere</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= user['_id'] %></td>
        <td><%= user['matches'] %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>